name: Build Docker Images

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage1: ["jupyter"]
        stage2: ["jupyter-scipy"]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Maximize build space üõ†
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc

      - name: Set up QEMU (for docker buildx) üê≥
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx (for multi-arch builds) üê≥
        uses: docker/setup-buildx-action@v2

      - name: Checkout Repo ‚ö°Ô∏è
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Stage 1
        id: build_stage1
        uses: docker/build-push-action@v3
        with:
          context: ./notebook-servers/${{ matrix.stage1 }}
          push: true
          tags: |
            ghcr.io/opengptx/notebook-servers/${{ matrix.stage1 }}:${{ github.run_id }}
            ghcr.io/opengptx/notebook-servers/${{ matrix.stage1 }}:latest

      - name: Build and push Stage 2
        id: build_stage2
        uses: docker/build-push-action@v3
        with:
          context: ./notebook-servers/${{ matrix.stage2 }}
          build-args: GCR=ghcr.io/opengptx
          push: true
          tags: |
            ghcr.io/opengptx/notebook-servers/${{ matrix.stage2 }}:${{ github.run_id }}
            ghcr.io/opengptx/notebook-servers/${{ matrix.stage2 }}:latest
